-- MOBILE FFLAG CLEANUP
-- No print(), warn(), or diagnostic output.
-- Each setting is applied inside pcall().
-- Chrome and mobile-supported UI flags are retained.

local function apply(name, value)
    pcall(function()
        setfflag(name, value)
    end)
end

local function applyMany(value, names)
    for _, name in ipairs(names) do
        apply(name, value)
    end
end

-- TELEMETRY FLAGS

applyMany("False", {
    "AddMoreSysTrayTelemetry",
    "AddPlaySessionIdTelemetry",
    "AddToDecryptionTelemetry",
    "AddUniverseIDToTelemetryV2FRMStats",
    "AICOUseTelemetryV2",
    "AndroidDebugHeapTelemetry",
    "AndroidMajorFaultsRateTelemetry",
    "AndroidOnTrimMemoryLevelTelemetry",
    "AndroidOomScoreTelemetry",
    "AppConfigurationAddTimeIntervalInTelemetry",
    "AppConfigurationAddUrlInTelemetry",
    "AppConfigurationAddUserIdInTelemetry",
    "AssetProviderByteRangeTelemetry",
    "AssetProviderSendTelemetryForIfRequestIsSentToNewAdDomain",
    "AssetRequestTelemetryAddCacheSourceField2",
    "AudioWiringTelemetryForAudioSpeechToText",
    "AudioWiringTelemetryForAudioTextToSpeech",
    "AvatarChangeTelemetryBatchFlush",
    "AvatarChangeTelemetryImmediateSend",
    "AvatarChatServiceTelemetryIncludeServerFeatures",
    "AvatarClothingAndDecalTelemetry3",
    "BadgesApiUsageTelemetryEnabled",
    "BaseGuiSelectedObjectUpdates",
    "BrowserTrackerIdTelemetryEnabled",
    "CapsMissRegularTelemetry",
    "CapsMissUnassignedTelemetry",
    "CaptureServiceSendAssetUploadFailureTelemetry",
    "CaptureServiceUpdateUploadTelemetry",
    "CheckFixLuaTelemetryBoolTypes",
    "CleanUpTeamCreateDeprecatedTelemetry",
    "CLI_147010_ReportAttributesWithHangTelemetry2",
    "EnableInExpChatRewrite3",
    "EnableInExpChatSummary6",
    "EnableSummarySystemMessage",
    "IASReportNewActionTypes",
    "ReplicatorTelemetryServerAuthorityMode",
    "ReportAssetRequestV1Telemetry",
    "ReportAssetRequestV2Telemetry",
    "VideoEnableL2aSessionTelemetry2",
    "VideoEnableL2bSessionTelemetry2",
    "VideoEnableUsageTelemetry",
    "MeshSimplificationTelemetry",
    "PerformanceControlFixTelemetryName",
    "PerformanceControlFttAdditionalTelemetryEnabled",
    "ReportTextureStreamingTelemetry7",
    "ReportVisibilityAndIslandTelemetry",
    "WebBrowserMemoryTelemetryEnabled",
    "WebBrowserPreInitializeMemoryTelemetry",
    "WebBrowserSTM6353MemoryTelemetry",
})

-- APP THEME AND SOCIAL UI

applyMany("False", {
    "AbuseReportMenuV2",
    "AbuseReportMenuV2_IXP",
    "AbuseReportTabSelectionHighlightCutoffFixEnabled",
    "AccessibilityPageUseFoundationToggle",
    "AddAutoTranslateToLoadingScreen",
    "AddFriendsBannersNewUI_exp_IXP",
    "AddFriendsBannersRefactor",
    "AddFriendsCINewIcon_exp_IXP",
    "AddFriendsUserListEnabled_v2",
    "AddFriendsUserListEnabled_v2_IXP",
    "AddIGMToSideSheet3",
    "AddTraversalHistory699v1",
    "AddTraversalHistoryReactMenuButtons",
    "AdServiceEnabled",
    "AESEnableTimedOptions3",
    "AgeBasedUXHomepageVerificationBannerLockIcon",
    "AIDiffMessage1",
    "AIRephraseSettingEnabled3",
    "AmendNewGuiSelectionHighlights",
    "AppChatInExperienceRenameToRobloxChat",
    "AppChatPresenceStoreMigration_v1_IXP",
    "AppChatRebrandIconUpdates",
    "AppChatRebrandIconUpdatesNew",
    "AppChatRebrandInNonChrome",
    "AppChatRebrandStringUpdates",
    "AppChatUniversalAppNavbarNewConfig",
    "AXBackgroundsInAvatarBustThumbnails",
    "AXBackgroundsInAvatarThumbnails",
    "AXBackgroundsInHeadshotThumbnails",
    "AXBackgroundsInHeadshotThumbnails_IXP",
    "AXCatalogMakeupSupport10",
    "AXCommunityAvatarsMakeupEquipping",
    "AXEnableFoundationSegmentedMenu_IXP",
    "AXInspectAndBuyMakeupSupport",
    "AXMakeupEquipping",
    "AXMigrateSystemSliderToFoundationSlider2",
    "AXNewRobuxBalanceButton2",
    "AXTimedOptionsSalesTypeFilter",
    "BuilderSansNavbarFlagSize",
    "BuilderSansNavbarLabelsFix2",
    "ChatSummariesSettingEnabled3",
    "ChatTranslationEnableSystemMessage",
    "ConnectionsHubLayerExposure_IXP",
    "CreateConnectionsHub_v6",
    "CreateConnectionsHub_v6_IXP",
    "DecoupleScreenGuiFromPurchasePromptApp",
    "DefaultKidsToDarkTheme2",
    "DefaultKidsToDarkTheme2_IXP",
    "EnableAccountSwitcherFoundationDesign9",
    "EnableAccountSwitcherLoginV2Correction",
    "EnableAccountSwitcherRedesignIXP",
    "EnableAudioTextToSpeech2",
    "EnableAudioTextToSpeech2_PlaceFilter",
    "EnableConsoleExpControls684",
    "EnableConsoleExpControlsV4",
    "EnableCoreContentThemeUseFoundationButton",
    "EnableCoreContentThemeUseFoundationButton_IXP",
    "EnableDesktopGameJoinCard_v5",
    "EnableDesktopGameJoinCard_v5_IXP",
    "EnableEventDetailsNewModalImprovements",
    "EnableEventDetailsNewModalIXP5",
    "EnableExpChatNewSystemMessagesExperimentation",
    "EnableFlyoutSidePanel15",
    "EnableFlyoutUncheckedBadge2",
    "EnableInExperienceShop3",
    "EnableInGameMenuChrome",
    "EnableInGameMenuChromeABTest2",
    "EnableInGameMenuChromeABTest3",
    "EnableInGameMenuChromeABTest4",
    "EnableInGameMenuChromeSignalAPI",
    "EnableInGameMenuChromeUI",
    "EnableInGameMenuModernization",
    "EnableInGameMenuSongbirdABTest",
    "EnableInspectAndBuyV2RootFlag2",
    "EnableNavBarLabels3",
    "EnableNonFlyoutUncheckedBadge2",
    "EnablePartyPageCarouselExperimentation4",
    "EnablePartyTabNumberedBadge6",
    "EnablePromptAgeCheck",
    "EnablePromptAgeCheckListener",
    "EnableSummarySystemMessageOnLua",
    "EnableWhiteOrGreyRobuxIcon",
    "ExpChatCanShowFriendsTabRC1_IXP",
    "ExpChatDictatedSpeechEnabled",
    "ExpChatDictation3",
    "ExpChatDictation3_IXP",
    "ExpChatEnableCrossAgeChatActivity",
    "ExpChatEnableFOMOUpsell",
    "ExpChatEnableFriendsTabRC1",
    "ExpChatGetLabelAndIconFromUtilUnibarHoldout",
    "ExpChatNewInputBar4",
    "ExpChatNewInputBar4_IXP",
    "ExpChatNewInputBarDictation",
    "ExpChatShowGlobalChatTooltip",
    "ExpChatUseGuacForCrossAgeChat",
    "FixUnibarRefactoringInTopBarApp",
    "FocusNavOutOfSubmenu",
    "FoundationButtonEnableLoadingState",
    "FoundationButtonLabelTypography",
    "FoundationButtonLoadingHideTextWithIcon",
    "FoundationButtonSubEmphasisInverseStateLayer",
    "FoundationButtonWidthAutoSize",
    "FoundationChipBeta",
    "FoundationChipDesignUpdate",
    "FoundationChipSelectable",
    "FoundationDialogAnimation2",
    "FoundationEnableNewButtonSizes",
    "FoundationFixDisablingForIconButtons",
    "FoundationRobuxIconMigration",
    "FoundationToastButtonsFillRightToLeft",
    "FoundationToggleBetaUpdate",
    "FoundationToggleDefaultPlacement",
    "FoundationToggleEndPlacementJustifyContent",
    "FoundationToggleVisualUpdate",
    "FriendRequestModalIxpEnabled_IXP",
    "FriendRequestModalRevampV4",
    "FriendRequestModalRevampV4_IXP",
    "FriendsPageUnifiedOpenProfileLogic",
    "FriendsPageViewBtnEnabled",
    "FriendsPageViewBtnEnabled_IXP",
    "FriendsPageViewBtnWidth_IXP",
    "GuiSelectionRepeatFInts",
    "IEMFocusNavSupportNewButtons2",
    "IEMFocusNavToButtons",
    "IEMSettingsGroups709_IXP",
    "IGMChangeCapturesToGallery",
    "IGMChangeGalleryHeaderIcon",
    "JoinCardAgeCheckUpsell_V3",
    "JoinCardAgeCheckUpsell_V3_IXP",
    "KidsThemeBlueColorsIxpEnabled_IXP",
    "LuaAppBadgeDetailsEnabled6_IXP",
    "LuaAppChangeRecommendedGamesTitle",
    "LuaAppChartsAppUseHoverTile",
    "LuaAppChartsAppUseHoverTile_IXP",
    "LuaAppCompositionAppChat",
    "LuaAppCompositionCharts",
    "LuaAppCompositionFixDetailClip",
    "LuaAppCompositionHome",
    "LuaAppCompositionHome_IXP",
    "LuaAppCompositionHomeHeaderFullBleed",
    "LuaAppCompositionLegacyLayout",
    "LuaAppCompositionSduiEnabled",
    "LuaAppCompositionSupport",
    "LuaAppCompositionTopBarFullBleed",
    "LuaAppEnableFoundationColors7",
    "LuaAppFoundationColorsABTest7",
    "LuaAppPlayButtonAmpAgeCheckFlow",
    "LuaAppPlayButtonUpdates2",
    "LuaAppPlayButtonUpdatesIxp3",
    "LuaAppSduiEdpEnabled2_IXP",
    "LuaAppSearchGridTiles2",
    "LuaAppUnifyPlayButtonAllSurfacesIxp",
    "LuaAppUnifyPlayButtonAllSurfacesIxp2",
    "LuaAppUnifyPlayButtonAllSurfacesIxp3",
    "LuaAppUnifyPlayButtonAllSurfacesIxp5",
    "LuaAppUnifyPlayButtonTile2",
    "LuaAppUnifyPlayButtonTileIxp",
    "LuaAppUpdateFoundationPlayButtonForTiles",
    "LuaAppUpdatePlayButtonText_IXP",
    "LuaAppUseFoundationCheckbox_IXP",
    "LuaAppUseNewTilePadding",
    "LuaStartPageFoundationPill",
    "MomentsDarkAppNavBar",
    "MomentsFixSkeletonNavBarInset",
    "MomentsTabReactiveIXP",
    "NewGuiSelectionHighlights",
    "NewPeoplePageIcons5",
    "ProfilePlatformCTAsRefactor_V3",
    "ProfilePlatformCTAsRefactor_V3_IXP",
    "QRCodeCopyUpdates_v2",
    "QRCodeFriendRequestNotificationV2",
    "RefactorHelpPage5",
    "RefactorHelpPage5_IXP",
    "RefactorMenuConfirmationButtons2_IXP",
    "RefactorMenuConfirmationButtons5",
    "RefactorPeoplePage9",
    "RefactorPeoplePage9_IXP",
    "RefactorUnifiedPurchasePrompt",
    "RemapAnimationR6ToR15Rig",
    "RenameRespawnConfirmationPage",
    "RenderUnifiedLighting16",
    "RenderUnifiedLightingNew",
    "SduiShowToastAction_v2_IXP",
    "SquadsPresenceStoreMigration_IXP",
    "StreamNotificationUXDropdown2",
    "SupportTimedOptionsinPerformPurchase",
    "SwitchOverToAbuseReportMenuV2_IXP",
    "TextChatEnableUniverseChatTabs11",
    "TopBarRefactor2_IXP",
    "TopBarSignalizeHealthBar4",
    "TopBarSignalizeKeepOutAreas5",
    "TopBarSignalizeMenuOpen",
    "TopBarSignalizeScreenSize2",
    "TopBarSignalizeSetCores",
    "UIBloxUseFoundationButton3_IXP",
    "UIBloxUseFoundationButton5_IXP",
    "UIBloxUseFoundationButtonInGame2_IXP",
    "UIBloxUseFoundationButtonInGame_IXP",
    "UIBloxUseFoundationSkeleton",
    "UIBloxUseFoundationSkeleton_IXP",
    "UnibarHoldoutChatIconUseNewIconSize",
    "UseNewHurtOverlayAnimation",
    "UseNewHurtOverlayImage",
    "UseNewPlayerList3",
    "UseNewRobloxIconInNotifications",
})

-- FEATURES TO ENABLE

applyMany("True", {
    "AddFriendsPresenceStoreMigration_v3_IXP",
    "AddFriendsPresenceStoreMigration_v4_IXP",
    "AgeBasedUXHomepageVerificationBannerGreyButton",
    "AppThemeClassicForAll",
    "AppThemeClassicNativeApi",
    "AppThemeClassicPerDevice",
    "AppThemeClassicReuseKidsStorageKey",
    "AppThemeClassicUnlockable",
    "AvatarChatServiceEnabled",
    "AXCustomizeMakeupSupport4",
    "AXEnableSlotBasedEditor3",
    "ConnectionsHubLayerExposure",
    "EnableClassicThemeAvailable",
    "EnableDynamicHeadVoiceChat",
    "EnableHomeRobloxLogo",
    "EnableHomeRobloxLogo_IXP",
    "EnableSelfViewPublicBeta",
    "ExpChatPresetChatEnabled10",
    "ExpChatPresetChatFixesEnabled",
    "ExpChatPresetChatIXPExposure_IXP",
    "FriendSortedByPresenceSignalsImplementation_v2_IXP",
    "FriendsPageUserListEnabled_v2",
    "FriendsPageUserListEnabled_v2_IXP",
    "Order66",
    "ProfilePlatformPresenceStoreMigration_v1_IXP",
    "SelfViewExpressionTracking",
    "SocialExperienceJoinPresenceStoreMigration_v1_IXP",
    "SocialTabsPagePresenceSignalsMigration",
    "SoundsUsePhysicalVelocity",
    "UIBloxToastFoundationButtonSizing",
})

-- NUMERIC SETTINGS
-- Keep the values as strings, matching your original commands.

apply("PartyVoiceLaunchFlowTelemetryThrottle", "0")
apply("PerfDataOnTelemetryV2ThrottleHundredthsPercent", "0")
apply("SurfaceControllerErrorTelemetryThrottleHundredthsPercent", "0")
apply("RelocateMobileMenuButtonsVariant", "0")

-- Intentionally omitted from the original list:
-- AddMachineIDInstallerTelemetry
-- DebugRenderForceTechnologyVoxel
-- DebugGraphicsPreferD3D11FL10
-- DataModelPatcherForceLocal
-- AnimationLodFacsDistanceMax
-- AnimationLodFacsDistanceMin
-- AnimationLodFacsVisibilityDenominator
-- NewInGameMenuPercentRollout3
-- UseNewPlayerListConsole_IXP
-- IxpNewLayersForRegistration
